# Generated by Django 4.2.6 on 2023-11-13 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tts_app", "0002_alter_student_school_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="department_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tts_app.department"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tts_app.school"
            ),
        ),
    ]
