# Generated by Django 4.2.6 on 2023-11-13 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tts_app", "0005_alter_cohort_cohort_name_alter_dean_school_email_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="lecturer",
            name="idx_lecturer_department_name",
        ),
        migrations.RemoveField(
            model_name="lecturer",
            name="department_name",
        ),
        migrations.AddField(
            model_name="lecturer",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tts_app.department",
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tts_app.school"
            ),
        ),
        migrations.AddIndex(
            model_name="lecturer",
            index=models.Index(
                fields=["department"], name="idx_lecturer_department_name"
            ),
        ),
    ]
