# Generated by Django 4.2.6 on 2023-11-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tts_app", "0006_remove_lecturer_idx_lecturer_department_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="department_name",
            new_name="department",
        ),
        migrations.AlterField(
            model_name="lectureroom",
            name="room_location",
            field=models.CharField(max_length=20),
        ),
    ]
