# Generated by Django 4.2.6 on 2023-11-13 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tts_app", "0007_rename_department_name_student_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dean",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tts_app.school",
            ),
        ),
    ]
