# Generated by Django 4.2.6 on 2023-11-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tts_app", "0008_dean_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="unit_code",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
