# Generated by Django 4.2.6 on 2023-11-13 18:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("tts_app", "0009_unit_unit_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phoneNumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None, unique=True
            ),
        ),
    ]
