# Generated by Django 4.2.6 on 2023-11-13 18:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("tts_app", "0010_student_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="dean",
            name="phoneNumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None, unique=True
            ),
        ),
        migrations.AddField(
            model_name="lecturer",
            name="phoneNumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None, unique=True
            ),
        ),
    ]
