# Generated by Django 4.2.6 on 2023-11-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tts_app", "0011_dean_phonenumber_lecturer_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="admission_number",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
