# Generated by Django 4.2.6 on 2023-11-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tts_app", "0014_courses"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Courses",
            new_name="Course",
        ),
    ]
