# Generated by Django 4.2.6 on 2023-11-13 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tts_app", "0015_rename_courses_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tts_app.course",
            ),
        ),
    ]
